CREATE PROCEDURE SHOW_MY_ORDERS
@CLIENT_NUMBER INT
AS
SELECT o.ORDER_NUMBER, c.CLIENT_NUMBER, c.FIRST_NAME, c.LAST_NAME, p.PRODUCT_NUMBER, p.PRODUCT_NAME, o.ORDER_QUANTITY, o.TOTAL_ORDER_COST
FROM Orders as o
INNER JOIN Clients as c ON o.CLIENT_NUMBER = c.CLIENT_NUMBER
INNER JOIN Products as p ON p.PRODUCT_NUMBER = o.PRODUCT_NUMBER
WHERE o.CLIENT_NUMBER = @CLIENT_NUMBER