CREATE PROCEDURE INSERT_NEW_CLIENT
@USERNAME varchar(50),
@PASS int,
@FIRST_NAME varchar(50),
@LAST_NAME varchar(50),
@CREDIT_CARD_NUMBER decimal
AS
INSERT INTO Clients(USERNAME, PASS, FIRST_NAME, LAST_NAME, CREDIT_CARD_NUMBER) values(@USERNAME, @PASS, @FIRST_NAME, @LAST_NAME, @CREDIT_CARD_NUMBER);