CREATE PROCEDURE UPDATE_QUANTITY_IN_STOCK
@ORDER_QUANTITY INT,
@PRODUCT_NUMBER INT
AS
UPDATE Products SET QUANTITY_IN_STOCK = (QUANTITY_IN_STOCK - @ORDER_QUANTITY) WHERE @PRODUCT_NUMBER = PRODUCT_NUMBER





