CREATE PROCEDURE INSERT_NEW_ORDER
@CLIENT_NUMBER INT,
@PRODUCT_NUMBER INT,
@ORDER_QUANTITY INT
AS
INSERT INTO Orders(CLIENT_NUMBER, PRODUCT_NUMBER, ORDER_QUANTITY) VALUES(@CLIENT_NUMBER, @PRODUCT_NUMBER, @ORDER_QUANTITY)





