CREATE PROCEDURE CHECK_PASSWORD_USERNAME_CLIENT
@USERNAME varchar(50),
@PASS varchar(50)
AS 
BEGIN
    IF EXISTS (SELECT * FROM Clients WHERE USERNAME = @USERNAME AND PASS=@PASS)
        SELECT 1
    ELSE
        SELECT 0  
END