CREATE PROCEDURE UPDATE_TOTAL_ORDER_COST
@ORDER_QUANTITY INT,
@PRODUCT_NUMBER INT
AS
UPDATE Orders SET TOTAL_ORDER_COST = @ORDER_QUANTITY*(SELECT COST FROM Products WHERE @PRODUCT_NUMBER = PRODUCT_NUMBER)
