CREATE PROCEDURE ADD_PRODUCT_QUANTITY
@PRODUCT_NAME varchar(50),
@QUANTITY_IN_STOCK varchar(50)
AS
UPDATE Products SET QUANTITY_IN_STOCK = QUANTITY_IN_STOCK + @QUANTITY_IN_STOCK WHERE PRODUCT_NAME = @PRODUCT_NAME