CREATE PROCEDURE SHOW_ALL_MY_PRODUCTS
@PROVIDER_NUMBER INT
AS
SELECT PRODUCT_NUMBER , PRODUCT_NAME, PROVIDER_NUMBER, COST, QUANTITY_IN_STOCK FROM Products
WHERE PROVIDER_NUMBER = @PROVIDER_NUMBER
 