CREATE PROCEDURE CHECK_IF_PRODUCT_EXIST
@PRODUCT_NAME varchar(50)
AS
BEGIN
IF EXISTS (SELECT * FROM Products as p WHERE PRODUCT_NAME = @PRODUCT_NAME)
        SELECT 1
    ELSE
        SELECT 0  
END